// Code generated by ent, DO NOT EDIT.

package part

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/edanko/nx/cmd/moses-api/internal/adapters/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProject), v))
	})
}

// Section applies equality check predicate on the "section" field. It's identical to SectionEQ.
func Section(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSection), v))
	})
}

// Pos applies equality check predicate on the "pos" field. It's identical to PosEQ.
func Pos(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPos), v))
	})
}

// Quality applies equality check predicate on the "quality" field. It's identical to QualityEQ.
func Quality(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldQuality), v))
	})
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// Length applies equality check predicate on the "length" field. It's identical to LengthEQ.
func Length(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLength), v))
	})
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWidth), v))
	})
}

// Thickness applies equality check predicate on the "thickness" field. It's identical to ThicknessEQ.
func Thickness(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldThickness), v))
	})
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCount), v))
	})
}

// Nested applies equality check predicate on the "nested" field. It's identical to NestedEQ.
func Nested(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNested), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProject), v))
	})
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldProject), v))
	})
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldProject), v...))
	})
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldProject), v...))
	})
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldProject), v))
	})
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldProject), v))
	})
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldProject), v))
	})
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldProject), v))
	})
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldProject), v))
	})
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldProject), v))
	})
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldProject), v))
	})
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldProject), v))
	})
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldProject), v))
	})
}

// SectionEQ applies the EQ predicate on the "section" field.
func SectionEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSection), v))
	})
}

// SectionNEQ applies the NEQ predicate on the "section" field.
func SectionNEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSection), v))
	})
}

// SectionIn applies the In predicate on the "section" field.
func SectionIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSection), v...))
	})
}

// SectionNotIn applies the NotIn predicate on the "section" field.
func SectionNotIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSection), v...))
	})
}

// SectionGT applies the GT predicate on the "section" field.
func SectionGT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSection), v))
	})
}

// SectionGTE applies the GTE predicate on the "section" field.
func SectionGTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSection), v))
	})
}

// SectionLT applies the LT predicate on the "section" field.
func SectionLT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSection), v))
	})
}

// SectionLTE applies the LTE predicate on the "section" field.
func SectionLTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSection), v))
	})
}

// SectionContains applies the Contains predicate on the "section" field.
func SectionContains(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSection), v))
	})
}

// SectionHasPrefix applies the HasPrefix predicate on the "section" field.
func SectionHasPrefix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSection), v))
	})
}

// SectionHasSuffix applies the HasSuffix predicate on the "section" field.
func SectionHasSuffix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSection), v))
	})
}

// SectionEqualFold applies the EqualFold predicate on the "section" field.
func SectionEqualFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSection), v))
	})
}

// SectionContainsFold applies the ContainsFold predicate on the "section" field.
func SectionContainsFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSection), v))
	})
}

// PosEQ applies the EQ predicate on the "pos" field.
func PosEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPos), v))
	})
}

// PosNEQ applies the NEQ predicate on the "pos" field.
func PosNEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPos), v))
	})
}

// PosIn applies the In predicate on the "pos" field.
func PosIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPos), v...))
	})
}

// PosNotIn applies the NotIn predicate on the "pos" field.
func PosNotIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPos), v...))
	})
}

// PosGT applies the GT predicate on the "pos" field.
func PosGT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPos), v))
	})
}

// PosGTE applies the GTE predicate on the "pos" field.
func PosGTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPos), v))
	})
}

// PosLT applies the LT predicate on the "pos" field.
func PosLT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPos), v))
	})
}

// PosLTE applies the LTE predicate on the "pos" field.
func PosLTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPos), v))
	})
}

// PosContains applies the Contains predicate on the "pos" field.
func PosContains(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPos), v))
	})
}

// PosHasPrefix applies the HasPrefix predicate on the "pos" field.
func PosHasPrefix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPos), v))
	})
}

// PosHasSuffix applies the HasSuffix predicate on the "pos" field.
func PosHasSuffix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPos), v))
	})
}

// PosEqualFold applies the EqualFold predicate on the "pos" field.
func PosEqualFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPos), v))
	})
}

// PosContainsFold applies the ContainsFold predicate on the "pos" field.
func PosContainsFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPos), v))
	})
}

// QualityEQ applies the EQ predicate on the "quality" field.
func QualityEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldQuality), v))
	})
}

// QualityNEQ applies the NEQ predicate on the "quality" field.
func QualityNEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldQuality), v))
	})
}

// QualityIn applies the In predicate on the "quality" field.
func QualityIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldQuality), v...))
	})
}

// QualityNotIn applies the NotIn predicate on the "quality" field.
func QualityNotIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldQuality), v...))
	})
}

// QualityGT applies the GT predicate on the "quality" field.
func QualityGT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldQuality), v))
	})
}

// QualityGTE applies the GTE predicate on the "quality" field.
func QualityGTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldQuality), v))
	})
}

// QualityLT applies the LT predicate on the "quality" field.
func QualityLT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldQuality), v))
	})
}

// QualityLTE applies the LTE predicate on the "quality" field.
func QualityLTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldQuality), v))
	})
}

// QualityContains applies the Contains predicate on the "quality" field.
func QualityContains(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldQuality), v))
	})
}

// QualityHasPrefix applies the HasPrefix predicate on the "quality" field.
func QualityHasPrefix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldQuality), v))
	})
}

// QualityHasSuffix applies the HasSuffix predicate on the "quality" field.
func QualityHasSuffix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldQuality), v))
	})
}

// QualityEqualFold applies the EqualFold predicate on the "quality" field.
func QualityEqualFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldQuality), v))
	})
}

// QualityContainsFold applies the ContainsFold predicate on the "quality" field.
func QualityContainsFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldQuality), v))
	})
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldType), v))
	})
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldType), v...))
	})
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldType), v...))
	})
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldType), v))
	})
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldType), v))
	})
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldType), v))
	})
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldType), v))
	})
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldType), v))
	})
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldType), v))
	})
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldType), v))
	})
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldType), v))
	})
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldType), v))
	})
}

// LengthEQ applies the EQ predicate on the "length" field.
func LengthEQ(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLength), v))
	})
}

// LengthNEQ applies the NEQ predicate on the "length" field.
func LengthNEQ(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLength), v))
	})
}

// LengthIn applies the In predicate on the "length" field.
func LengthIn(vs ...float64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLength), v...))
	})
}

// LengthNotIn applies the NotIn predicate on the "length" field.
func LengthNotIn(vs ...float64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLength), v...))
	})
}

// LengthGT applies the GT predicate on the "length" field.
func LengthGT(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLength), v))
	})
}

// LengthGTE applies the GTE predicate on the "length" field.
func LengthGTE(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLength), v))
	})
}

// LengthLT applies the LT predicate on the "length" field.
func LengthLT(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLength), v))
	})
}

// LengthLTE applies the LTE predicate on the "length" field.
func LengthLTE(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLength), v))
	})
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWidth), v))
	})
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldWidth), v))
	})
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...float64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldWidth), v...))
	})
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...float64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldWidth), v...))
	})
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldWidth), v))
	})
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldWidth), v))
	})
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldWidth), v))
	})
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldWidth), v))
	})
}

// ThicknessEQ applies the EQ predicate on the "thickness" field.
func ThicknessEQ(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldThickness), v))
	})
}

// ThicknessNEQ applies the NEQ predicate on the "thickness" field.
func ThicknessNEQ(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldThickness), v))
	})
}

// ThicknessIn applies the In predicate on the "thickness" field.
func ThicknessIn(vs ...float64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldThickness), v...))
	})
}

// ThicknessNotIn applies the NotIn predicate on the "thickness" field.
func ThicknessNotIn(vs ...float64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldThickness), v...))
	})
}

// ThicknessGT applies the GT predicate on the "thickness" field.
func ThicknessGT(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldThickness), v))
	})
}

// ThicknessGTE applies the GTE predicate on the "thickness" field.
func ThicknessGTE(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldThickness), v))
	})
}

// ThicknessLT applies the LT predicate on the "thickness" field.
func ThicknessLT(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldThickness), v))
	})
}

// ThicknessLTE applies the LTE predicate on the "thickness" field.
func ThicknessLTE(v float64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldThickness), v))
	})
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCount), v))
	})
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCount), v))
	})
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCount), v...))
	})
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCount), v...))
	})
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCount), v))
	})
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCount), v))
	})
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCount), v))
	})
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCount), v))
	})
}

// NestedEQ applies the EQ predicate on the "nested" field.
func NestedEQ(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNested), v))
	})
}

// NestedNEQ applies the NEQ predicate on the "nested" field.
func NestedNEQ(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNested), v))
	})
}

// NestedIn applies the In predicate on the "nested" field.
func NestedIn(vs ...int64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNested), v...))
	})
}

// NestedNotIn applies the NotIn predicate on the "nested" field.
func NestedNotIn(vs ...int64) predicate.Part {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Part(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNested), v...))
	})
}

// NestedGT applies the GT predicate on the "nested" field.
func NestedGT(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNested), v))
	})
}

// NestedGTE applies the GTE predicate on the "nested" field.
func NestedGTE(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNested), v))
	})
}

// NestedLT applies the LT predicate on the "nested" field.
func NestedLT(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNested), v))
	})
}

// NestedLTE applies the LTE predicate on the "nested" field.
func NestedLTE(v int64) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNested), v))
	})
}

// HasNests applies the HasEdge predicate on the "nests" edge.
func HasNests() predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(NestsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, NestsTable, NestsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNestsWith applies the HasEdge predicate on the "nests" edge with a given conditions (other predicates).
func HasNestsWith(preds ...predicate.Nest) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(NestsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, NestsTable, NestsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Part) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Part) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Part) predicate.Part {
	return predicate.Part(func(s *sql.Selector) {
		p(s.Not())
	})
}
