app:
  environment: development
  shutdownTimeout: 5s
db:
  host: 192.168.1.164
  port: 5432
  user: postgres
  password: mysecretpassword
  database: moses
  sslMode: disable
nats:
  host: 192.168.1.164
  port: 4222
debug:
  host: 0.0.0.0
  port: 4000
http:
  host: 0.0.0.0
  port: 3000
  readTimeout: 5s
  writeTimeout: 10s
  idleTimeout: 120s
grpc:
  host: 0.0.0.0
  port: 3001
  serverMinTime: 5m
  serverTime: 2h
  serverTimeout: 20s
  connTime: 10s
  connTimeout: 20s
