// Code generated by ent, DO NOT EDIT.

package remnant

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the remnant type in the database.
	Label = "remnant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldQuality holds the string denoting the quality field in the database.
	FieldQuality = "quality"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldLength holds the string denoting the length field in the database.
	FieldLength = "length"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldThickness holds the string denoting the thickness field in the database.
	FieldThickness = "thickness"
	// EdgeNest holds the string denoting the nest edge name in mutations.
	EdgeNest = "nest"
	// EdgeRemnantUsed holds the string denoting the remnant_used edge name in mutations.
	EdgeRemnantUsed = "remnant_used"
	// Table holds the table name of the remnant in the database.
	Table = "remnants"
	// NestTable is the table that holds the nest relation/edge.
	NestTable = "remnants"
	// NestInverseTable is the table name for the Nest entity.
	// It exists in this package in order to avoid circular dependency with the "nest" package.
	NestInverseTable = "nests"
	// NestColumn is the table column denoting the nest relation/edge.
	NestColumn = "nest_remnant"
	// RemnantUsedTable is the table that holds the remnant_used relation/edge.
	RemnantUsedTable = "nests"
	// RemnantUsedInverseTable is the table name for the Nest entity.
	// It exists in this package in order to avoid circular dependency with the "nest" package.
	RemnantUsedInverseTable = "nests"
	// RemnantUsedColumn is the table column denoting the remnant_used relation/edge.
	RemnantUsedColumn = "remnant_remnant_used"
)

// Columns holds all SQL columns for remnant fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldQuality,
	FieldType,
	FieldLength,
	FieldWidth,
	FieldThickness,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "remnants"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"nest_remnant",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// QualityValidator is a validator for the "quality" field. It is called by the builders before save.
	QualityValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// LengthValidator is a validator for the "length" field. It is called by the builders before save.
	LengthValidator func(float64) error
	// WidthValidator is a validator for the "width" field. It is called by the builders before save.
	WidthValidator func(float64) error
	// ThicknessValidator is a validator for the "thickness" field. It is called by the builders before save.
	ThicknessValidator func(float64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
