// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: launch/v1/launch.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KindStatus int32

const (
	KindStatus_KIND_STATUS_UNSPECIFIED KindStatus = 0
	KindStatus_KIND_STATUS_DRAFT       KindStatus = 1
	KindStatus_KIND_STATUS_PUBLISHED   KindStatus = 2
)

// Enum value maps for KindStatus.
var (
	KindStatus_name = map[int32]string{
		0: "KIND_STATUS_UNSPECIFIED",
		1: "KIND_STATUS_DRAFT",
		2: "KIND_STATUS_PUBLISHED",
	}
	KindStatus_value = map[string]int32{
		"KIND_STATUS_UNSPECIFIED": 0,
		"KIND_STATUS_DRAFT":       1,
		"KIND_STATUS_PUBLISHED":   2,
	}
)

func (x KindStatus) Enum() *KindStatus {
	p := new(KindStatus)
	*p = x
	return p
}

func (x KindStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KindStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_launch_v1_launch_proto_enumTypes[0].Descriptor()
}

func (KindStatus) Type() protoreflect.EnumType {
	return &file_launch_v1_launch_proto_enumTypes[0]
}

func (x KindStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KindStatus.Descriptor instead.
func (KindStatus) EnumDescriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{0}
}

// Kind object
type Kind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description *string    `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status      KindStatus `protobuf:"varint,4,opt,name=status,proto3,enum=launch.v1.KindStatus" json:"status,omitempty"`
}

func (x *Kind) Reset() {
	*x = Kind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kind) ProtoMessage() {}

func (x *Kind) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kind.ProtoReflect.Descriptor instead.
func (*Kind) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{0}
}

func (x *Kind) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Kind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kind) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Kind) GetStatus() KindStatus {
	if x != nil {
		return x.Status
	}
	return KindStatus_KIND_STATUS_UNSPECIFIED
}

type CreateKindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description *string    `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status      KindStatus `protobuf:"varint,4,opt,name=status,proto3,enum=launch.v1.KindStatus" json:"status,omitempty"`
}

func (x *CreateKindRequest) Reset() {
	*x = CreateKindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKindRequest) ProtoMessage() {}

func (x *CreateKindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKindRequest.ProtoReflect.Descriptor instead.
func (*CreateKindRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKindRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateKindRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKindRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateKindRequest) GetStatus() KindStatus {
	if x != nil {
		return x.Status
	}
	return KindStatus_KIND_STATUS_UNSPECIFIED
}

type CreateKindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateKindResponse) Reset() {
	*x = CreateKindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKindResponse) ProtoMessage() {}

func (x *CreateKindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKindResponse.ProtoReflect.Descriptor instead.
func (*CreateKindResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{2}
}

type DeleteKindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteKindRequest) Reset() {
	*x = DeleteKindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKindRequest) ProtoMessage() {}

func (x *DeleteKindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKindRequest.ProtoReflect.Descriptor instead.
func (*DeleteKindRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteKindRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteKindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKindResponse) Reset() {
	*x = DeleteKindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKindResponse) ProtoMessage() {}

func (x *DeleteKindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKindResponse.ProtoReflect.Descriptor instead.
func (*DeleteKindResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{4}
}

type MakeKindPublishedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MakeKindPublishedRequest) Reset() {
	*x = MakeKindPublishedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeKindPublishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeKindPublishedRequest) ProtoMessage() {}

func (x *MakeKindPublishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeKindPublishedRequest.ProtoReflect.Descriptor instead.
func (*MakeKindPublishedRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{5}
}

func (x *MakeKindPublishedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MakeKindPublishedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MakeKindPublishedResponse) Reset() {
	*x = MakeKindPublishedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeKindPublishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeKindPublishedResponse) ProtoMessage() {}

func (x *MakeKindPublishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeKindPublishedResponse.ProtoReflect.Descriptor instead.
func (*MakeKindPublishedResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{6}
}

type MakeKindDraftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MakeKindDraftRequest) Reset() {
	*x = MakeKindDraftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeKindDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeKindDraftRequest) ProtoMessage() {}

func (x *MakeKindDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeKindDraftRequest.ProtoReflect.Descriptor instead.
func (*MakeKindDraftRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{7}
}

func (x *MakeKindDraftRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MakeKindDraftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MakeKindDraftResponse) Reset() {
	*x = MakeKindDraftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeKindDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeKindDraftResponse) ProtoMessage() {}

func (x *MakeKindDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeKindDraftResponse.ProtoReflect.Descriptor instead.
func (*MakeKindDraftResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{8}
}

type ChangeKindDescriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ChangeKindDescriptionRequest) Reset() {
	*x = ChangeKindDescriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeKindDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKindDescriptionRequest) ProtoMessage() {}

func (x *ChangeKindDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeKindDescriptionRequest.ProtoReflect.Descriptor instead.
func (*ChangeKindDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeKindDescriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeKindDescriptionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ChangeKindDescriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeKindDescriptionResponse) Reset() {
	*x = ChangeKindDescriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeKindDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKindDescriptionResponse) ProtoMessage() {}

func (x *ChangeKindDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeKindDescriptionResponse.ProtoReflect.Descriptor instead.
func (*ChangeKindDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{10}
}

type ChangeKindNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeKindNameRequest) Reset() {
	*x = ChangeKindNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeKindNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKindNameRequest) ProtoMessage() {}

func (x *ChangeKindNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeKindNameRequest.ProtoReflect.Descriptor instead.
func (*ChangeKindNameRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeKindNameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeKindNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeKindNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeKindNameResponse) Reset() {
	*x = ChangeKindNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeKindNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKindNameResponse) ProtoMessage() {}

func (x *ChangeKindNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeKindNameResponse.ProtoReflect.Descriptor instead.
func (*ChangeKindNameResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{12}
}

// GetKindRequest is a request data to read kind
type GetKindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetKindRequest) Reset() {
	*x = GetKindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKindRequest) ProtoMessage() {}

func (x *GetKindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKindRequest.ProtoReflect.Descriptor instead.
func (*GetKindRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{13}
}

func (x *GetKindRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetKindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind *Kind `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *GetKindResponse) Reset() {
	*x = GetKindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKindResponse) ProtoMessage() {}

func (x *GetKindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKindResponse.ProtoReflect.Descriptor instead.
func (*GetKindResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{14}
}

func (x *GetKindResponse) GetKind() *Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

type GetKindByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetKindByNameRequest) Reset() {
	*x = GetKindByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKindByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKindByNameRequest) ProtoMessage() {}

func (x *GetKindByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKindByNameRequest.ProtoReflect.Descriptor instead.
func (*GetKindByNameRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{15}
}

func (x *GetKindByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetKindByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind *Kind `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *GetKindByNameResponse) Reset() {
	*x = GetKindByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKindByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKindByNameResponse) ProtoMessage() {}

func (x *GetKindByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKindByNameResponse.ProtoReflect.Descriptor instead.
func (*GetKindByNameResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{16}
}

func (x *GetKindByNameResponse) GetKind() *Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

// ListKindRequest is a request data to read all kind for a given page
type ListKindsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  *int32      `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	After  *string     `protobuf:"bytes,2,opt,name=after,proto3,oneof" json:"after,omitempty"`
	Status *KindStatus `protobuf:"varint,3,opt,name=status,proto3,enum=launch.v1.KindStatus,oneof" json:"status,omitempty"`
}

func (x *ListKindsRequest) Reset() {
	*x = ListKindsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKindsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKindsRequest) ProtoMessage() {}

func (x *ListKindsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKindsRequest.ProtoReflect.Descriptor instead.
func (*ListKindsRequest) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{17}
}

func (x *ListKindsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListKindsRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *ListKindsRequest) GetStatus() KindStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return KindStatus_KIND_STATUS_UNSPECIFIED
}

// ListKindResponse list of all kinds
type ListKindsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kinds []*Kind `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	After string  `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit int32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` //  int32 total = 4;
}

func (x *ListKindsResponse) Reset() {
	*x = ListKindsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_v1_launch_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKindsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKindsResponse) ProtoMessage() {}

func (x *ListKindsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKindsResponse.ProtoReflect.Descriptor instead.
func (*ListKindsResponse) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{18}
}

func (x *ListKindsResponse) GetKinds() []*Kind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *ListKindsResponse) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ListKindsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_launch_v1_launch_proto protoreflect.FileDescriptor

var file_launch_v1_launch_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x2e, 0x76, 0x31, 0x22, 0x90, 0x01, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9d, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x4d, 0x61, 0x6b, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x26, 0x0a, 0x14, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x66,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x4d, 0x61, 0x6b, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x50, 0x0a, 0x1c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e,
	0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x3c, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22,
	0x9b, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x19, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6c, 0x61, 0x75,
	0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x48, 0x02, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x61, 0x66, 0x74,
	0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x66, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x05, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x66, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2a, 0x5b, 0x0a, 0x0a, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x15, 0x0a, 0x11, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x45, 0x44,
	0x10, 0x02, 0x32, 0xf8, 0x05, 0x0a, 0x0b, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x1c, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1c, 0x2e, 0x6c, 0x61,
	0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x11, 0x4d, 0x61, 0x6b, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x23, 0x2e,
	0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x4d, 0x61, 0x6b, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x66, 0x74, 0x12, 0x1f, 0x2e, 0x6c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x72,
	0x61, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x61, 0x75,
	0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44,
	0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x15,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x6c, 0x61, 0x75,
	0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x19, 0x2e, 0x6c, 0x61, 0x75,
	0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x52, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69, 0x6e,
	0x64, 0x73, 0x12, 0x1b, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4b, 0x69, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a,
	0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61,
	0x75, 0x6e, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_launch_v1_launch_proto_rawDescOnce sync.Once
	file_launch_v1_launch_proto_rawDescData = file_launch_v1_launch_proto_rawDesc
)

func file_launch_v1_launch_proto_rawDescGZIP() []byte {
	file_launch_v1_launch_proto_rawDescOnce.Do(func() {
		file_launch_v1_launch_proto_rawDescData = protoimpl.X.CompressGZIP(file_launch_v1_launch_proto_rawDescData)
	})
	return file_launch_v1_launch_proto_rawDescData
}

var file_launch_v1_launch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_launch_v1_launch_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_launch_v1_launch_proto_goTypes = []interface{}{
	(KindStatus)(0),                       // 0: launch.v1.KindStatus
	(*Kind)(nil),                          // 1: launch.v1.Kind
	(*CreateKindRequest)(nil),             // 2: launch.v1.CreateKindRequest
	(*CreateKindResponse)(nil),            // 3: launch.v1.CreateKindResponse
	(*DeleteKindRequest)(nil),             // 4: launch.v1.DeleteKindRequest
	(*DeleteKindResponse)(nil),            // 5: launch.v1.DeleteKindResponse
	(*MakeKindPublishedRequest)(nil),      // 6: launch.v1.MakeKindPublishedRequest
	(*MakeKindPublishedResponse)(nil),     // 7: launch.v1.MakeKindPublishedResponse
	(*MakeKindDraftRequest)(nil),          // 8: launch.v1.MakeKindDraftRequest
	(*MakeKindDraftResponse)(nil),         // 9: launch.v1.MakeKindDraftResponse
	(*ChangeKindDescriptionRequest)(nil),  // 10: launch.v1.ChangeKindDescriptionRequest
	(*ChangeKindDescriptionResponse)(nil), // 11: launch.v1.ChangeKindDescriptionResponse
	(*ChangeKindNameRequest)(nil),         // 12: launch.v1.ChangeKindNameRequest
	(*ChangeKindNameResponse)(nil),        // 13: launch.v1.ChangeKindNameResponse
	(*GetKindRequest)(nil),                // 14: launch.v1.GetKindRequest
	(*GetKindResponse)(nil),               // 15: launch.v1.GetKindResponse
	(*GetKindByNameRequest)(nil),          // 16: launch.v1.GetKindByNameRequest
	(*GetKindByNameResponse)(nil),         // 17: launch.v1.GetKindByNameResponse
	(*ListKindsRequest)(nil),              // 18: launch.v1.ListKindsRequest
	(*ListKindsResponse)(nil),             // 19: launch.v1.ListKindsResponse
}
var file_launch_v1_launch_proto_depIdxs = []int32{
	0,  // 0: launch.v1.Kind.status:type_name -> launch.v1.KindStatus
	0,  // 1: launch.v1.CreateKindRequest.status:type_name -> launch.v1.KindStatus
	1,  // 2: launch.v1.GetKindResponse.kind:type_name -> launch.v1.Kind
	1,  // 3: launch.v1.GetKindByNameResponse.kind:type_name -> launch.v1.Kind
	0,  // 4: launch.v1.ListKindsRequest.status:type_name -> launch.v1.KindStatus
	1,  // 5: launch.v1.ListKindsResponse.kinds:type_name -> launch.v1.Kind
	2,  // 6: launch.v1.KindService.CreateKind:input_type -> launch.v1.CreateKindRequest
	4,  // 7: launch.v1.KindService.DeleteKind:input_type -> launch.v1.DeleteKindRequest
	6,  // 8: launch.v1.KindService.MakeKindPublished:input_type -> launch.v1.MakeKindPublishedRequest
	8,  // 9: launch.v1.KindService.MakeKindDraft:input_type -> launch.v1.MakeKindDraftRequest
	10, // 10: launch.v1.KindService.ChangeKindDescription:input_type -> launch.v1.ChangeKindDescriptionRequest
	12, // 11: launch.v1.KindService.ChangeKindName:input_type -> launch.v1.ChangeKindNameRequest
	14, // 12: launch.v1.KindService.GetKind:input_type -> launch.v1.GetKindRequest
	16, // 13: launch.v1.KindService.GetKindByName:input_type -> launch.v1.GetKindByNameRequest
	18, // 14: launch.v1.KindService.ListKinds:input_type -> launch.v1.ListKindsRequest
	3,  // 15: launch.v1.KindService.CreateKind:output_type -> launch.v1.CreateKindResponse
	5,  // 16: launch.v1.KindService.DeleteKind:output_type -> launch.v1.DeleteKindResponse
	7,  // 17: launch.v1.KindService.MakeKindPublished:output_type -> launch.v1.MakeKindPublishedResponse
	9,  // 18: launch.v1.KindService.MakeKindDraft:output_type -> launch.v1.MakeKindDraftResponse
	11, // 19: launch.v1.KindService.ChangeKindDescription:output_type -> launch.v1.ChangeKindDescriptionResponse
	13, // 20: launch.v1.KindService.ChangeKindName:output_type -> launch.v1.ChangeKindNameResponse
	15, // 21: launch.v1.KindService.GetKind:output_type -> launch.v1.GetKindResponse
	17, // 22: launch.v1.KindService.GetKindByName:output_type -> launch.v1.GetKindByNameResponse
	19, // 23: launch.v1.KindService.ListKinds:output_type -> launch.v1.ListKindsResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_launch_v1_launch_proto_init() }
func file_launch_v1_launch_proto_init() {
	if File_launch_v1_launch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_launch_v1_launch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeKindPublishedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeKindPublishedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeKindDraftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeKindDraftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeKindDescriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeKindDescriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeKindNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeKindNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKindByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKindByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKindsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_v1_launch_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKindsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_launch_v1_launch_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_launch_v1_launch_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_launch_v1_launch_proto_msgTypes[17].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_launch_v1_launch_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_launch_v1_launch_proto_goTypes,
		DependencyIndexes: file_launch_v1_launch_proto_depIdxs,
		EnumInfos:         file_launch_v1_launch_proto_enumTypes,
		MessageInfos:      file_launch_v1_launch_proto_msgTypes,
	}.Build()
	File_launch_v1_launch_proto = out.File
	file_launch_v1_launch_proto_rawDesc = nil
	file_launch_v1_launch_proto_goTypes = nil
	file_launch_v1_launch_proto_depIdxs = nil
}
