version: '3'

tasks:
  run:
    desc: Run launch-api
    dir: ./cmd/launch-api
    cmds:
      - go run .

  build:
    desc: Build launch-api
    cmds:
      - go build -o launch-api.exe ./cmd/launch-api

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - golangci-lint run

  generate:
    desc: Generate Go code
    cmds:
      - go generate

  test:
    desc: Go test
    cmds:
      - go test ./...

  bench:
    desc: Run go benchmarks
    cmds:
      - go test ./... -bench=. -run="Benchmark*"

  format:
    desc: Run source files with golines and goimports
    cmds:
      - buf format -w
      - for f in $(find . -name *.go -print); do golines --base-formatter="goimports -local $(go list -m)" -w $f; done

  cover:
    desc: Go code coverage
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out | grep ^total
      # - go tool cover -html=coverage.out
      - rm -f coverage.out
