// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: kind/v1/kind.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind object
type Kind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status      string  `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Kind) Reset() {
	*x = Kind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kind) ProtoMessage() {}

func (x *Kind) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kind.ProtoReflect.Descriptor instead.
func (*Kind) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{0}
}

func (x *Kind) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Kind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kind) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Kind) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateKindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status      string  `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateKindRequest) Reset() {
	*x = CreateKindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKindRequest) ProtoMessage() {}

func (x *CreateKindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKindRequest.ProtoReflect.Descriptor instead.
func (*CreateKindRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKindRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateKindRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKindRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateKindRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateKindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateKindResponse) Reset() {
	*x = CreateKindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKindResponse) ProtoMessage() {}

func (x *CreateKindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKindResponse.ProtoReflect.Descriptor instead.
func (*CreateKindResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{2}
}

type DeleteKindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteKindRequest) Reset() {
	*x = DeleteKindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKindRequest) ProtoMessage() {}

func (x *DeleteKindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKindRequest.ProtoReflect.Descriptor instead.
func (*DeleteKindRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteKindRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteKindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKindResponse) Reset() {
	*x = DeleteKindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKindResponse) ProtoMessage() {}

func (x *DeleteKindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKindResponse.ProtoReflect.Descriptor instead.
func (*DeleteKindResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{4}
}

type MakeKindPublishedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MakeKindPublishedRequest) Reset() {
	*x = MakeKindPublishedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeKindPublishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeKindPublishedRequest) ProtoMessage() {}

func (x *MakeKindPublishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeKindPublishedRequest.ProtoReflect.Descriptor instead.
func (*MakeKindPublishedRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{5}
}

func (x *MakeKindPublishedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MakeKindPublishedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MakeKindPublishedResponse) Reset() {
	*x = MakeKindPublishedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeKindPublishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeKindPublishedResponse) ProtoMessage() {}

func (x *MakeKindPublishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeKindPublishedResponse.ProtoReflect.Descriptor instead.
func (*MakeKindPublishedResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{6}
}

type MakeKindDraftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MakeKindDraftRequest) Reset() {
	*x = MakeKindDraftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeKindDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeKindDraftRequest) ProtoMessage() {}

func (x *MakeKindDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeKindDraftRequest.ProtoReflect.Descriptor instead.
func (*MakeKindDraftRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{7}
}

func (x *MakeKindDraftRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MakeKindDraftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MakeKindDraftResponse) Reset() {
	*x = MakeKindDraftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeKindDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeKindDraftResponse) ProtoMessage() {}

func (x *MakeKindDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeKindDraftResponse.ProtoReflect.Descriptor instead.
func (*MakeKindDraftResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{8}
}

type ChangeKindDescriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ChangeKindDescriptionRequest) Reset() {
	*x = ChangeKindDescriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeKindDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKindDescriptionRequest) ProtoMessage() {}

func (x *ChangeKindDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeKindDescriptionRequest.ProtoReflect.Descriptor instead.
func (*ChangeKindDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeKindDescriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeKindDescriptionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ChangeKindDescriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeKindDescriptionResponse) Reset() {
	*x = ChangeKindDescriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeKindDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKindDescriptionResponse) ProtoMessage() {}

func (x *ChangeKindDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeKindDescriptionResponse.ProtoReflect.Descriptor instead.
func (*ChangeKindDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{10}
}

type ChangeKindNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeKindNameRequest) Reset() {
	*x = ChangeKindNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeKindNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKindNameRequest) ProtoMessage() {}

func (x *ChangeKindNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeKindNameRequest.ProtoReflect.Descriptor instead.
func (*ChangeKindNameRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeKindNameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeKindNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeKindNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeKindNameResponse) Reset() {
	*x = ChangeKindNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeKindNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKindNameResponse) ProtoMessage() {}

func (x *ChangeKindNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeKindNameResponse.ProtoReflect.Descriptor instead.
func (*ChangeKindNameResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{12}
}

// GetKindRequest is a request data to read kind
type GetKindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetKindRequest) Reset() {
	*x = GetKindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKindRequest) ProtoMessage() {}

func (x *GetKindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKindRequest.ProtoReflect.Descriptor instead.
func (*GetKindRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{13}
}

func (x *GetKindRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetKindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind *Kind `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *GetKindResponse) Reset() {
	*x = GetKindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKindResponse) ProtoMessage() {}

func (x *GetKindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKindResponse.ProtoReflect.Descriptor instead.
func (*GetKindResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{14}
}

func (x *GetKindResponse) GetKind() *Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

type GetKindByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetKindByNameRequest) Reset() {
	*x = GetKindByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKindByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKindByNameRequest) ProtoMessage() {}

func (x *GetKindByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKindByNameRequest.ProtoReflect.Descriptor instead.
func (*GetKindByNameRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{15}
}

func (x *GetKindByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetKindByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind *Kind `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *GetKindByNameResponse) Reset() {
	*x = GetKindByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKindByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKindByNameResponse) ProtoMessage() {}

func (x *GetKindByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKindByNameResponse.ProtoReflect.Descriptor instead.
func (*GetKindByNameResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{16}
}

func (x *GetKindByNameResponse) GetKind() *Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

type CountKindsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *string `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *CountKindsRequest) Reset() {
	*x = CountKindsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountKindsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountKindsRequest) ProtoMessage() {}

func (x *CountKindsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountKindsRequest.ProtoReflect.Descriptor instead.
func (*CountKindsRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{17}
}

func (x *CountKindsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type CountKindsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CountKindsResponse) Reset() {
	*x = CountKindsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountKindsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountKindsResponse) ProtoMessage() {}

func (x *CountKindsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountKindsResponse.ProtoReflect.Descriptor instead.
func (*CountKindsResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{18}
}

func (x *CountKindsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ListKindRequest is a request data to read all kind for a given page
type ListKindsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page   *int32  `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit  *int32  `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Status *string `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *ListKindsRequest) Reset() {
	*x = ListKindsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKindsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKindsRequest) ProtoMessage() {}

func (x *ListKindsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKindsRequest.ProtoReflect.Descriptor instead.
func (*ListKindsRequest) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{19}
}

func (x *ListKindsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListKindsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListKindsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

// ListKindResponse list of all kinds
type ListKindsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kinds []*Kind `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Page  int32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total int32   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListKindsResponse) Reset() {
	*x = ListKindsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kind_v1_kind_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKindsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKindsResponse) ProtoMessage() {}

func (x *ListKindsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kind_v1_kind_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKindsResponse.ProtoReflect.Descriptor instead.
func (*ListKindsResponse) Descriptor() ([]byte, []int) {
	return file_kind_v1_kind_proto_rawDescGZIP(), []int{20}
}

func (x *ListKindsResponse) GetKinds() []*Kind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *ListKindsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListKindsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListKindsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_kind_v1_kind_proto protoreflect.FileDescriptor

var file_kind_v1_kind_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6b, 0x69, 0x6e, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x79, 0x0a,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x86, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1b,
	0x0a, 0x19, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x4d,
	0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44,
	0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x50, 0x0a, 0x1c,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1f,
	0x0a, 0x1d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x3b, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x18, 0x0a, 0x16,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6b, 0x69, 0x6e, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x2a,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6e, 0x64,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x3b, 0x0a, 0x11, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4b,
	0x69, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x12, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x69, 0x6e, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x81, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x78, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x6b, 0x69, 0x6e, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x05, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0x9b, 0x06,
	0x0a, 0x0b, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x2e, 0x6b, 0x69,
	0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x1a, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x4d,
	0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x12, 0x21, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61,
	0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x4d, 0x61, 0x6b, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x66, 0x74, 0x12, 0x1d, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x66, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x25, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x51, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x17, 0x2e,
	0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69,
	0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x45, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x12, 0x1a,
	0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x69,
	0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6b, 0x69, 0x6e,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4b,
	0x69, 0x6e, 0x64, 0x73, 0x12, 0x19, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69,
	0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x69, 0x6e, 0x64,
	0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kind_v1_kind_proto_rawDescOnce sync.Once
	file_kind_v1_kind_proto_rawDescData = file_kind_v1_kind_proto_rawDesc
)

func file_kind_v1_kind_proto_rawDescGZIP() []byte {
	file_kind_v1_kind_proto_rawDescOnce.Do(func() {
		file_kind_v1_kind_proto_rawDescData = protoimpl.X.CompressGZIP(file_kind_v1_kind_proto_rawDescData)
	})
	return file_kind_v1_kind_proto_rawDescData
}

var file_kind_v1_kind_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_kind_v1_kind_proto_goTypes = []interface{}{
	(*Kind)(nil),                          // 0: kind.v1.Kind
	(*CreateKindRequest)(nil),             // 1: kind.v1.CreateKindRequest
	(*CreateKindResponse)(nil),            // 2: kind.v1.CreateKindResponse
	(*DeleteKindRequest)(nil),             // 3: kind.v1.DeleteKindRequest
	(*DeleteKindResponse)(nil),            // 4: kind.v1.DeleteKindResponse
	(*MakeKindPublishedRequest)(nil),      // 5: kind.v1.MakeKindPublishedRequest
	(*MakeKindPublishedResponse)(nil),     // 6: kind.v1.MakeKindPublishedResponse
	(*MakeKindDraftRequest)(nil),          // 7: kind.v1.MakeKindDraftRequest
	(*MakeKindDraftResponse)(nil),         // 8: kind.v1.MakeKindDraftResponse
	(*ChangeKindDescriptionRequest)(nil),  // 9: kind.v1.ChangeKindDescriptionRequest
	(*ChangeKindDescriptionResponse)(nil), // 10: kind.v1.ChangeKindDescriptionResponse
	(*ChangeKindNameRequest)(nil),         // 11: kind.v1.ChangeKindNameRequest
	(*ChangeKindNameResponse)(nil),        // 12: kind.v1.ChangeKindNameResponse
	(*GetKindRequest)(nil),                // 13: kind.v1.GetKindRequest
	(*GetKindResponse)(nil),               // 14: kind.v1.GetKindResponse
	(*GetKindByNameRequest)(nil),          // 15: kind.v1.GetKindByNameRequest
	(*GetKindByNameResponse)(nil),         // 16: kind.v1.GetKindByNameResponse
	(*CountKindsRequest)(nil),             // 17: kind.v1.CountKindsRequest
	(*CountKindsResponse)(nil),            // 18: kind.v1.CountKindsResponse
	(*ListKindsRequest)(nil),              // 19: kind.v1.ListKindsRequest
	(*ListKindsResponse)(nil),             // 20: kind.v1.ListKindsResponse
}
var file_kind_v1_kind_proto_depIdxs = []int32{
	0,  // 0: kind.v1.GetKindResponse.kind:type_name -> kind.v1.Kind
	0,  // 1: kind.v1.GetKindByNameResponse.kind:type_name -> kind.v1.Kind
	0,  // 2: kind.v1.ListKindsResponse.kinds:type_name -> kind.v1.Kind
	1,  // 3: kind.v1.KindService.CreateKind:input_type -> kind.v1.CreateKindRequest
	3,  // 4: kind.v1.KindService.DeleteKind:input_type -> kind.v1.DeleteKindRequest
	5,  // 5: kind.v1.KindService.MakeKindPublished:input_type -> kind.v1.MakeKindPublishedRequest
	7,  // 6: kind.v1.KindService.MakeKindDraft:input_type -> kind.v1.MakeKindDraftRequest
	9,  // 7: kind.v1.KindService.ChangeKindDescription:input_type -> kind.v1.ChangeKindDescriptionRequest
	11, // 8: kind.v1.KindService.ChangeKindName:input_type -> kind.v1.ChangeKindNameRequest
	13, // 9: kind.v1.KindService.GetKind:input_type -> kind.v1.GetKindRequest
	15, // 10: kind.v1.KindService.GetKindByName:input_type -> kind.v1.GetKindByNameRequest
	17, // 11: kind.v1.KindService.CountKinds:input_type -> kind.v1.CountKindsRequest
	19, // 12: kind.v1.KindService.ListKinds:input_type -> kind.v1.ListKindsRequest
	2,  // 13: kind.v1.KindService.CreateKind:output_type -> kind.v1.CreateKindResponse
	4,  // 14: kind.v1.KindService.DeleteKind:output_type -> kind.v1.DeleteKindResponse
	6,  // 15: kind.v1.KindService.MakeKindPublished:output_type -> kind.v1.MakeKindPublishedResponse
	8,  // 16: kind.v1.KindService.MakeKindDraft:output_type -> kind.v1.MakeKindDraftResponse
	10, // 17: kind.v1.KindService.ChangeKindDescription:output_type -> kind.v1.ChangeKindDescriptionResponse
	12, // 18: kind.v1.KindService.ChangeKindName:output_type -> kind.v1.ChangeKindNameResponse
	14, // 19: kind.v1.KindService.GetKind:output_type -> kind.v1.GetKindResponse
	16, // 20: kind.v1.KindService.GetKindByName:output_type -> kind.v1.GetKindByNameResponse
	18, // 21: kind.v1.KindService.CountKinds:output_type -> kind.v1.CountKindsResponse
	20, // 22: kind.v1.KindService.ListKinds:output_type -> kind.v1.ListKindsResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kind_v1_kind_proto_init() }
func file_kind_v1_kind_proto_init() {
	if File_kind_v1_kind_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kind_v1_kind_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeKindPublishedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeKindPublishedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeKindDraftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeKindDraftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeKindDescriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeKindDescriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeKindNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeKindNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKindByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKindByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountKindsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountKindsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKindsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kind_v1_kind_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKindsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kind_v1_kind_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_kind_v1_kind_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_kind_v1_kind_proto_msgTypes[17].OneofWrappers = []interface{}{}
	file_kind_v1_kind_proto_msgTypes[19].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kind_v1_kind_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kind_v1_kind_proto_goTypes,
		DependencyIndexes: file_kind_v1_kind_proto_depIdxs,
		MessageInfos:      file_kind_v1_kind_proto_msgTypes,
	}.Build()
	File_kind_v1_kind_proto = out.File
	file_kind_v1_kind_proto_rawDesc = nil
	file_kind_v1_kind_proto_goTypes = nil
	file_kind_v1_kind_proto_depIdxs = nil
}
