openapi: 3.0.0
x-stoplight:
  id: 0ab7655b1c428
info:
  version: 1.0.0
  title: kind
  description: TODO
  contact:
    name: Egor Danko
    email: qwertyone@gmail.com
servers:
  - url: 'http://{hostname}:3000/v1'
    variables:
      hostname:
        default: localhost
tags:
  - name: kind
    description: TODO
paths:
  /kinds:
    get:
      summary: List Kinds
      operationId: listKinds
      responses:
        '200':
          $ref: '#/components/responses/ListKindsResponse'
      description: Retrieves a list of kinds.
      tags:
        - kind
      parameters:
        - schema:
            type: string
          in: query
          name: after
        - schema:
            type: integer
            default: 20
          in: query
          name: limit
        - schema:
            type: string
            enum:
              - published
              - draft
            default: published
          in: query
          name: status
    post:
      summary: Create New Kind
      operationId: createKind
      responses:
        '204':
          description: Kind Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kind'
              examples: {}
        '400':
          description: Missing Required Information
        '409':
          description: Kind with this name already exists
      description: Create a new kind.
      requestBody:
        $ref: '#/components/requestBodies/CreateKindRequest'
      tags:
        - kind
  '/kinds/{id}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of an existing kind
    get:
      summary: Get Kind by ID
      tags:
        - kind
      responses:
        '200':
          $ref: '#/components/responses/GetKindResponse'
        '404':
          description: Kind Not Found
      operationId: getKind
      description: Retrieve the information of the kind with the matching kind ID.
    delete:
      summary: Delete Kind by ID
      operationId: deleteKind
      responses:
        '204':
          description: No Content
        '404':
          description: Kind Not Found
      description: Deletes existing kind.
      tags:
        - kind
  '/kinds/{id}/changeName':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of an existing kind
    post:
      summary: Change Kind Name
      operationId: changeKindName
      responses:
        '204':
          description: No Content
      requestBody:
        $ref: '#/components/requestBodies/ChangeKindName'
      tags:
        - kind
      description: Change existing kind name.
  '/kinds/{id}/changeDescription':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of an existing kind
    post:
      summary: Change Kind Description
      operationId: changeKindDescription
      responses:
        '204':
          description: No Content
      requestBody:
        $ref: '#/components/requestBodies/ChangeKindDescription'
      tags:
        - kind
      description: Change existing kind description.
  '/kinds/{id}/makePublished':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of an existing kind
    post:
      summary: Make Kind Published
      operationId: makeKindPublished
      responses:
        '204':
          description: No Content
      tags:
        - kind
      description: Change status of an existiong kind to published.
  '/kinds/{id}/makeDraft':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of an existing kind
    post:
      summary: Make Kind Draft
      operationId: makeKindDraft
      responses:
        '204':
          description: No Content
      tags:
        - kind
      description: Change status of an existiong kind to draft.
components:
  schemas:
    Kind:
      title: Kind
      type: object
      description: Kind model.
      properties:
        id:
          type: string
          description: Unique identifier for the given kind.
          format: uuid
        name:
          type: string
          description: Unique name for the given kind.
        description:
          type: string
          description: Description for the given kind.
        status:
          type: string
          enum:
            - published
            - draft
      required:
        - id
        - name
        - status
  responses:
    GetKindResponse:
      description: Get Kind Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Kind'
          examples:
            Got Draft Kind:
              value:
                id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                name: kindName
                description: some description
                status: draft
    ListKindsResponse:
      description: Paginated Kinds Response
      content:
        application/json:
          schema:
            type: object
            properties:
              kinds:
                type: array
                items:
                  $ref: '#/components/schemas/Kind'
              page:
                type: integer
              limit:
                type: integer
              total:
                type: integer
              after:
                type: string
            required:
              - kinds
              - limit
              - after
  requestBodies:
    CreateKindRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              status:
                type: string
            required:
              - name
              - status
          examples:
            Create Published Kind:
              value:
                name: kindName
                description: some description
                status: published
            Create Draft Kind:
              value:
                name: kindName
                description: some description
                status: draft
      description: Create Kind Request
    ChangeKindName:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
            required:
              - name
    ChangeKindDescription:
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
            required:
              - description
  examples: {}
